### PR TITLE
Validation

### PR DESCRIPTION
**Pull request by m-terra**
@bakito 

in this PR we use the official validation package from apimachinery. we had some problems with validating labels with "/" in the keys which is actually allowed.

for the new image and chart, do i need to increase the chart version and appVersion or will you do that?

cheers

### CODE REVIEW

**Comment by bakito** [comment]
@m-terra thank you for the fix

Chart and image are automatically updated during ther release process. There's nothing you need to change here.

**Comment by bakito** [comment]
@m-terra this is part of release https://github.com/bakito/k8s-event-logger-operator/releases/tag/v1.11.0

**Comment by m-terra** [comment]
> @m-terra this is part of release https://github.com/bakito/k8s-event-logger-operator/releases/tag/v1.11.0

@bakito but when i download release v1.11.0 the chart file has version v1.10.2

**Comment by bakito** [comment]
@m-terra where did you download the release from? 
The chart from https://charts.bakito.net/ look sof for me.

**Pull request merged**
